### ISSUE TITLE
Failed to activate the atomify package

### ISSUE THREAD

**Issue by saurabh10prabhune** [jaebradley/atomify#35]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atomify](https://github.com/jaebradley/atomify) package 0.3.0

### Stack Trace

Failed to activate the atomify package

```
At Cannot find module 'node-osascript'

Error: Cannot find module 'node-osascript'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/atomify/lib/atomify-view.js:3:43)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/atomify/lib/atomify.js:7:20)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.2/resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:887:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:242:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:623:1
```

### Commands

```
```

### Non-Core Packages

```
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-clock 0.1.8 
atomify 0.3.0 
gruvbox-plus-syntax 1.3.1 
hey-pane 1.0.0 
Hydrogen 1.16.0 
linter-write-good 0.9.0 
loved-syntax 1.0.1 
pristine-ui 1.0.15 
pure-syntax 0.2.1 
scroll-through-time 0.2.0 
toggler 0.3.0 
zentabs 0.8.8 
```

**Comment by jaebradley** [comment]
@saurabh10prabhune `atomify` is only supported for OSX

![image](https://user-images.githubusercontent.com/8136030/28243417-7848043e-6996-11e7-9aff-0cfdb38cdd9b.png)
