### ISSUE TITLE
Failed to load the atomify package

### ISSUE THREAD

**Issue by pushpalmazumder** [jaebradley/atomify#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atomify](https://github.com/jaebradley/atomify) package 0.6.0

### Stack Trace

Failed to load the atomify package

```
At Cannot find module 'react'

Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atomify/lib/atom/Main.js:11:14)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:565:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:479:25
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:321:22)
    at PackageManager.module.exports.PackageManager.loadPackages (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:473:25)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:812:34
```

### Commands

```
  7x -1:38.5.0 click (div.item-views)
```

### Non-Core Packages

```
aligner-php 1.1.1 
apex-syntax 0.1.0 
apex-ui 0.2.1 
atom-autocomplete-php 0.25.6 
atom-clock 0.1.13 
atom-php-test 0.0.3 
atomify 0.6.0 
autocomplete-php 0.3.7 
chestnut-light-atom-syntax 0.2.1 
dash-ui 0.4.1 
drunken-php 0.2.3 
hey-pane 1.0.0 
hyperclick-php 0.2.1 
intentions 1.1.2 
linter 2.2.0 
linter-php 1.3.2 
loved-syntax 1.0.2 
minimap-plus 4.29.2 
php-analyser 0.2.0 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.0 
php-debug 0.2.4 
php-extract-method 0.2.1 
php-fmt 0.1.2 
php-hyperclick 1.2.1 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-autocomplete-plus-legacy-php56 1.0.1 
php-integrator-base 3.0.1 
php-integrator-base-legacy-php56 1.0.1 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-navigation-legacy-php56 1.0.1 
php-integrator-refactoring 1.4.0 
php-integrator-refactoring-legacy-php56 1.0.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-refactoring 1.4.0 
php-server 0.7.0 
piatto-light-syntax 0.2.2 
pristine-ui 1.1.0 
project-manager 3.3.5 
pure-syntax 0.3.0 
scroll-through-time 0.2.0 
toggler 0.3.0 
zentabs 0.8.8 
```

**Comment by jaebradley** [comment]
![image](https://user-images.githubusercontent.com/8136030/28467066-9d344068-6dfc-11e7-8687-857bf188b3ea.png)

I have not added Windows support yet - the description says that this plugin is for Macs only. Apologies for the inconvenience, but I'm going to close this.
